'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Game.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AlienShot1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlienShot1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlienShot2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlienShot2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AlienShot3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlienShot3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Atmospheric_Pad() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Atmospheric_Pad", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Blue_Boss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue_Boss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Boss() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boss", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Boss_Laser() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Boss_Laser", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Boss1() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Boss1", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Cave_Ambience() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Cave_Ambience", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Cymbals() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Cymbals", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Enemy_Death() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Enemy_Death", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Enemy1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enemy1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Enemy2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enemy2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Enemy3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enemy3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EPIC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPIC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Epic_Orchestra() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Epic_Orchestra", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion_SoundBible_com_2019248186() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Explosion_SoundBible_com_2019248186", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explosion17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explosion17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion20() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion20", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Explosion9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Explosion9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FINAL_BEAM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FINAL_BEAM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fireball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fireball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Free_Kick_Sample_12_912_Free_Loops_com() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Free_Kick_Sample_12_912_Free_Loops_com", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Game_Theme() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Game_Theme", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Laser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Laser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Laser_Fire() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Laser_Fire", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Low_Explosion() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Low_Explosion", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Maniac_Single() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Maniac_Single", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MuzzleFlash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MuzzleFlash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PlayerShot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlayerShot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slo_Funk_Drum() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Slo_Funk_Drum", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Snare_Drum() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Snare_Drum", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property SpaceShip() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpaceShip", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Super_Synth() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Super_Synth", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Timer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Timer", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property whitebox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whitebox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
